### ISSUE TITLE
关于开发文档问题

### ISSUE THREAD

**Issue by DashBing** [audreyt/lingua-sinica-perlyuyan#2]
我觉得这个项目非常有潜力
但是就是没有相关文档解释
希望能够出一个专门的文档讲解替换的关键词之类的

（如果已经有了，请把链接之类的粘过来，可能是我没看到之类的）

**Comment by yingkai-liao** [comment]
https://github.com/audreyt/lingua-sinica-perlyuyan/blob/master/lib/Lingua/Sinica/PerlYuYan.pm
這隻檔下面的那堆應該足夠讓你看懂

**Comment by DashBing** [comment]
> https://github.com/audreyt/lingua-sinica-perlyuyan/blob/master/lib/Lingua/Sinica/PerlYuYan.pm 這隻檔下面的那堆應該足夠讓你看懂

没开通知，，，刚看到，的确看懂了
